return {
  "stevearc/conform.nvim",
  opts = {
    format_on_save = false,
    default_format_opts = {
      timeout_ms = 30000,
      format_on_save = false,
    },
    formatters_by_ft = {
      astro = { "prettierd" },
      javascript = { "prettierd" },
      javascriptreact = { "prettierd" },
      typescript = { "prettierd" },
      typescriptreact = { "prettierd" },
      vue = { "prettierd" },
      css = { "prettierd" },
      scss = { "prettierd" },
      less = { "prettierd" },
      html = { "prettierd" },
      json = { "prettierd" },
      jsonc = { "prettierd" },
      yaml = { "prettierd" },
      markdown = { "prettierd" },
      graphql = { "prettierd" },
      go = { "goimports", "gofumpt" },
      svelte = { "prettierd" },
      ["markdown.mdx"] = { "prettierd" },
    },
  },
}
